//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarsayyWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Urun()
        {
            this.Table_Resim = new HashSet<Table_Resim>();
        }
    
        public int Urunid { get; set; }
        public string Adi { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Markaid { get; set; }
    
        public virtual Table_Marka Table_Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Resim> Table_Resim { get; set; }
    }
}
