//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarsayyWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Kullanici_Rol
    {
        public int Kullanici_Rolid { get; set; }
        public int Rolid { get; set; }
        public int Kullanciid { get; set; }
    
        public virtual Table_Kullanici Table_Kullanici { get; set; }
        public virtual Table_Rol Table_Rol { get; set; }
    }
}
