//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VarsayyWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUrunler
    {
        public int Urunid { get; set; }
        public string Adi { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Markaid { get; set; }
    }
}
